"""Initial migration.

Revision ID: 616898df7610
Revises: 
Create Date: 2025-05-14 18:56:59.663850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616898df7610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_trials',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inclusion_criteria', sa.JSON(), nullable=False),
    sa.Column('exclusion_criteria', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('completion_date', sa.String(length=50), nullable=True),
    sa.Column('sponsor', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.String(length=50), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('min_age', sa.String(length=50), nullable=True),
    sa.Column('max_age', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('org_study_id', sa.String(length=100), nullable=False),
    sa.Column('secondary_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_study_id')
    )
    with op.batch_alter_table('clinical_trials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_trials_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_trials_status'), ['status'], unique=False)
        batch_op.create_index('ix_clinical_trials_title', ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinical_trials', schema=None) as batch_op:
        batch_op.drop_index('ix_clinical_trials_title')
        batch_op.drop_index(batch_op.f('ix_clinical_trials_status'))
        batch_op.drop_index(batch_op.f('ix_clinical_trials_phase'))

    op.drop_table('clinical_trials')
    # ### end Alembic commands ###
